variables:
  NewCodeRefBranch:
    value: $CI_DEFAULT_BRANCH
    description: "Define New code for feature branch"

stages:
  - codecheck

sonarqube:
  stage: codecheck
  image: registry.syntecclub.com/projectroot/cnc/buildmachine/cnclinuxbuildmachine:1.latest
  tags:
    - "docker_linux_x64"
    - "mel_license_nic"
  variables:
    GIT_DEPTH: 0
  before_script:
    - git config --global --add safe.directory '*'
    - if [[ $(git rev-parse --is-shallow-repository) == "true" ]]; then git fetch --unshallow; fi
  script:
    - cd $CI_PROJECT_DIR/Build
    - sudo chmod +x SQAnalysis.sh build.sh
    - bash ./SQAnalysis.sh
  artifacts:
    name: "BuildLog_SonarQube"
    when: always
    untracked: true
