##########################################
## Make File
##########################################
#
# Project build config setting
# To decide which combination of target platform and config mode need to build
# Rule: |Enable (Y:Build, N:Skip)|TargetPlatform|ConfigMode|
#
ProjectBuildConfig :=\
 |Y|Linux_x64|Debug|\
 |Y|Linux_x64|Release|\

#
# Include project build rule
#
include ../../../res/Build/ProjBuildRule.mk
